pipeline{
    agent{
        label 'agent-1'
    }
    environment{
        appVersion=''
        project='robshop'
    }
    options{
        ansiColor('xtrem')
    }
    stages{
        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                    """
                    }
                }
                
            }
        }

        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh """
                        cd 00-vpc
                        terraform destroy -auto-approve
                    """
                    }
                }
                
            }
        }
    
        stage('plan'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh"""
                        cd 00-vpc
                        terraform plan
                    """
                    }
                }
                
            }
        }

        stage('apply'){
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps{
                script{
                     withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                    """
                    }
                }
               
            }
        }

        stage('triggering sg fom vpc'){
            steps{
                build job: '10-sg'
            }
        }
    }
}