pipeline{
    agent{
        label 'agent-1'
    }
    environment{
        project='roboshop'
    }

    stages{
        stage('terraform init'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth',region:'us-east-1'){
                    sh"""
                        cd 10-sg
                        terraform init -reconfigure
                    """
                }
                }
            }
        }

        stage('terrafrom plan'){
            steps{  
                script{
                    withAWS(credentials: 'aws-auth',region:'us-east-1'){
                        sh"""
                            cd 10-sg
                            terraform plan
                        """
                }
                }
                
            }

        }

         stage('terrafrom apply'){
            steps{  
                script{
                    withAWS(credentials: 'aws-auth',region:'us-east-1'){
                        sh"""
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                }
                }
                
            }

        }

        stage('bastion eks alb acm'){
            parallel{
                stage('triggering bastion'){
                    steps{
                        script{
                            build job: '20-bastion'
                            propagate: false
                            wait: false
                        }
                    }
                    
                }
                stage('triggering acm'){
                    steps{
                        script{
                            build job: '60-acm'
                            propagete: false
                            wait:false
                        }
                    }
                   
                }
                stage('triggering eks'){
                        steps{
                            script{
                                build job: '80-eks'
                                propagate: false
                                wait: false
                            }
                        }
                    
                }

            }
        }

        stage('frontend-alb'){
            steps{
                script{
                    
                 build job: '70-frontend-alb'
                propagate: false
                wait: false
                }
               
            }
        }
    }

}