pipeline{
    agent{
        label 'agent-1'
    }
    environment{
        project='roboshop'
    }

    stages{
        stage(terraform init){
            steps{
                withAWS(credentials: 'aws-auth',region:'us-east-1'){
                    sh"""
                        cd 10-sg
                        terraform init -reconfigure
                    """
                }
            }
        }

        stage(terrafrom plan){
            steps{  
                withAWS(credentials: 'aws-auth',region:'us-east-1'){
                        sh"""
                            cd 10-sg
                            terraform plan
                        """
                }
            }

        }

         stage(terrafrom apply){
            steps{  
                withAWS(credentials: 'aws-auth',region:'us-east-1'){
                        sh"""
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                }
            }

        }

        stage(bastion eks alb acm){
            parallel{
                stage(triggering bastion){
                    build job: '20-bastion'
                    parameters:[

                    ]
                    propagate: false
                    wait: fasle
                }
                stage(triggering acm){
                    build job: '60-acm'
                    propagete: false
                    wait:false
                }
                stage(triggering eks){
                    build job: '80-eks'
                    propagate: false
                    wait: false
                }

            }
        }

        stage(frontend-alb){
            steps{
                build job: '70-frontend-alb'
                propagate: false
                wait: false
            }
        }
    }

}