pipeline{
    agent{
        label 'agent-1'
    }
    environment{
        appVersion=''
        project='robshop'
    }
    options{
        ansicolor('xtrem')
    }
    stages{
        stage(terraform init vpc){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                    """
                }
                }
                
            }
        }
    
        stage(terraform plan vpc){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh"""
                        cd 00-vpc
                        terraform plan
                    """
                }
                }
                
            }
        }

        stage(terraform apply){
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
            }
            steps{
                script{withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                    sh """
                        cd 00-vpc
                        terraform plan -auto-approve
                    """
                }
            }
                
            }
        }
    }
}